/* eslint-disable */
export enum ROLES {
  USER = 'USER',
  ADMIN = 'ADMIN',
  DIRECTOR = 'DIRECTOR',
  ESPECIALISTA = 'ESPECIALISTA',
  JASV = 'JASV',
  DIRECTOREJECUTIVO = 'DIRECTOREJECUTIVO',
  ANALISTA = 'ANALISTA'
  
}
